name: Actions

on: [push]

jobs:
    run-github:
        runs-on: ubuntu-latest
        steps:
            
            - name: simplerest
              uses: actions/checkout@v1 
            - name: Set up JDK 11
              uses: actions/setup-java@v2
              with:
                java-version: '11'
                distribution: 'adopt'
            - name: Test1
              run: echo $PWD                         
            - name: TEst
              run: |           
                cd /home/runner/work/Tedtci/Tedtci/testart/src/main/java/Mytest
                ls