name: Actions

on: [push]

jobs:
    run-github:
        runs-on: ubuntu-latest
        steps:
            - name: List files
              run: |
                pwd
                ls
            
            - name: simplerest
              uses: ashiq82/checkout@v1
              
            - name: List files after
              run: |
                pwd
                ls