name: Actions

on: [push]

jobs:
    run-github:
        runs-on: ubuntu-latest
        steps:
            - name: simplerest
              uses: ashiq82/Tedtci/blob/master/testart/src/main/java/Mytest/Testyt.java