name: Actions

on: [push]

jobs:
    run-github:
        runs-on: ubuntu-latest
        steps:
            - name: List files
              run: |
                pwd
                ls -a
            
            - name: simplerest
              uses: actions/checkout@v1
              
            - name: List files after
              run: |
                pwd
                ls -a
                
              
            - name: TEst
              uses: ./testart/src/main/java/Mytest/Testyt.java